export const LANGS = ['en', 'th'];

/**
 * Prose length limits, per language.
 *
 * Thai packs more meaning into the same character count — it has no inter-word
 * spaces and shorter function words — so a single cap calibrated on English
 * silently allows a much longer Thai finding. The Thai limits are ~60% of the
 * English ones, which is roughly where the two carry equivalent content.
 *
 * `sentences` is only enforced for English: Thai does not mark sentence
 * boundaries with terminal punctuation, so counting them is unreliable and the
 * character cap does the work instead.
 */
export const CAPS = {
  en: {
    chars: { title: 120, message: 300, impact: 300, suggestion: 400, evidence: 300 },
    sentences: { message: 2, impact: 2, suggestion: 3, evidence: 2 },
  },
  th: {
    chars: { title: 80, message: 180, impact: 180, suggestion: 240, evidence: 180 },
    sentences: null,
  },
};

const STRINGS = {
  en: {
    reportTitle: 'Code Review',
    labels: {
      verdict: 'Verdict',
      range: 'Reviewed range',
      scope: 'Scope',
      status: 'Status',
      reviewedCommit: 'Reviewed commit',
      previouslyReviewed: 'Previously reviewed',
      base: 'Base',
    },
    sections: {
      blocking: 'Blocking',
      warning: 'Warnings',
      suggestion: 'Suggestions',
      checks: 'Checks',
      commentChecks: 'Automated checks',
      limitations: 'Limitations',
      stillUnresolved: 'Still unresolved',
      newlyIntroduced: 'Newly introduced',
    },
    recommended: 'Recommended change',
    verdicts: {
      pass: 'Pass',
      pass_with_warnings: 'Pass with warnings',
      changes_required: 'Changes required',
      unable_to_complete: 'Unable to complete',
    },
    commentStatus: {
      pass: 'No blocking issues found — human approval still required',
      pass_with_warnings: 'Approved with comments — human approval still required',
      changes_required: 'Changes requested',
      unable_to_complete: 'Review incomplete',
    },
    checkStatus: {
      passed: 'Passed',
      failed: 'Failed',
      skipped: 'Skipped',
      not_available: 'Not available',
    },
    preExisting: 'Pre-existing, not introduced by this change.',
    reconsidered: 'Reconsidered since the previous review',
    scopeLine: (reviewed, changed, exclusions) =>
      `${reviewed} of ${changed} changed files` +
      (exclusions.length ? ` — ${exclusions.join('; ')}` : ''),
    resolvedNote: (ids) => `Resolved since the previous review: ${ids.join(', ')}.`,
    fullRerunNote: (reason) => `Reviewed the full PR rather than only the new commits: ${reason}`,
    disclaimer: 'This review was generated by an AI assistant and should be validated by a human reviewer.',
  },
  th: {
    reportTitle: 'ผลรีวิวโค้ด',
    labels: {
      verdict: 'ผลรีวิว',
      range: 'ช่วงที่รีวิว',
      scope: 'ขอบเขต',
      status: 'สถานะ',
      reviewedCommit: 'Commit ที่รีวิว',
      previouslyReviewed: 'รีวิวรอบก่อนที่',
      base: 'Base',
    },
    sections: {
      blocking: 'ต้องแก้ก่อน merge',
      warning: 'ข้อสังเกต',
      suggestion: 'ข้อเสนอแนะ',
      checks: 'ผลตรวจอัตโนมัติ',
      commentChecks: 'ผลตรวจอัตโนมัติ',
      limitations: 'ข้อจำกัดของการรีวิว',
      stillUnresolved: 'ยังไม่ได้แก้',
      newlyIntroduced: 'เพิ่งเจอใหม่',
    },
    recommended: 'แนะนำให้แก้เป็น',
    verdicts: {
      pass: 'ผ่าน',
      pass_with_warnings: 'ผ่านแบบมีข้อสังเกต',
      changes_required: 'ต้องแก้ไข',
      unable_to_complete: 'รีวิวไม่สมบูรณ์',
    },
    commentStatus: {
      pass: 'ไม่พบปัญหาที่ต้องแก้ก่อน merge — ยังต้องรอคนอนุมัติ',
      pass_with_warnings: 'ผ่านแบบมีข้อสังเกต — ยังต้องรอคนอนุมัติ',
      changes_required: 'ต้องแก้ไข',
      unable_to_complete: 'รีวิวไม่สมบูรณ์',
    },
    checkStatus: {
      passed: 'ผ่าน',
      failed: 'ไม่ผ่าน',
      skipped: 'ข้าม',
      not_available: 'รันไม่ได้',
    },
    preExisting: 'เป็นของเดิม ไม่ได้เกิดจากการแก้ครั้งนี้',
    reconsidered: 'เปลี่ยนข้อสรุปจากรีวิวรอบก่อน',
    scopeLine: (reviewed, changed, exclusions) =>
      `${reviewed} จาก ${changed} ไฟล์ที่เปลี่ยน` +
      (exclusions.length ? ` — ${exclusions.join('; ')}` : ''),
    resolvedNote: (ids) => `แก้แล้วตั้งแต่รีวิวรอบก่อน: ${ids.join(', ')}`,
    fullRerunNote: (reason) => `รีวิวเต็มทั้ง PR แทนที่จะรีวิวเฉพาะ commit ใหม่ เพราะ ${reason}`,
    disclaimer: 'รีวิวนี้สร้างโดย AI และควรได้รับการตรวจสอบโดยผู้รีวิวที่เป็นคน',
  },
};

export function strings(lang) {
  const table = STRINGS[lang];
  if (!table) throw new Error(`ไม่รองรับภาษา: ${lang}`);
  return table;
}
