export const LANGS = ['en', 'th'];

/**
 * Prose length limits, per language.
 *
 * Thai packs more meaning into the same character count — it has no inter-word
 * spaces and shorter function words — so a single cap calibrated on English
 * silently allows a much longer Thai finding. The Thai limits are ~60% of the
 * English ones, which is roughly where the two carry equivalent content.
 *
 * `sentences` is only enforced for English: Thai does not mark sentence
 * boundaries with terminal punctuation, so counting them is unreliable and the
 * character cap does the work instead.
 */
export const CAPS = {
  en: {
    chars: { title: 120, message: 300, impact: 300, suggestion: 400, evidence: 300 },
    sentences: { message: 2, impact: 2, suggestion: 3, evidence: 2 },
  },
  th: {
    chars: { title: 80, message: 180, impact: 180, suggestion: 240, evidence: 180 },
    sentences: null,
  },
};

/**
 * Structural chrome — identical in every language, by design.
 *
 * Headings, field labels and status values name things from the output
 * contract, and the team says them in English regardless of which language the
 * review is written in. Translating them would give one state two names.
 *
 * Sharing one object rather than repeating the values per language makes that
 * rule structural: a heading cannot drift into a translation, because there is
 * nowhere to put the translation.
 */
const CHROME = {
  reportTitle: 'Code Review',
  commentTitle: 'AI-assisted Code Review',
  labels: {
    verdict: 'Verdict',
    range: 'Reviewed range',
    scope: 'Scope',
    status: 'Status',
    reviewedCommit: 'Reviewed commit',
    previouslyReviewed: 'Previously reviewed',
    base: 'Base',
  },
  sections: {
    blocking: 'Blocking',
    warning: 'Warnings',
    suggestion: 'Suggestions',
    checks: 'Checks',
    commentChecks: 'Automated checks',
    limitations: 'Limitations',
    stillUnresolved: 'Still unresolved',
    newlyIntroduced: 'Newly introduced',
  },
  recommended: 'Recommended change',
  evidenceLabel: 'Evidence',
  verdicts: {
    pass: 'Pass',
    pass_with_warnings: 'Pass with warnings',
    changes_required: 'Changes required',
    unable_to_complete: 'Unable to complete',
  },
  checkStatus: {
    passed: 'Passed',
    failed: 'Failed',
    skipped: 'Skipped',
    not_available: 'Not available',
  },
};

/**
 * Sentences. These carry meaning rather than naming a contract value, so they
 * are written in the reader's language. A status term stays English even here —
 * only the clause around it is translated.
 */
const PROSE = {
  en: {
    commentStatus: {
      pass: 'No blocking issues found — human approval still required',
      pass_with_warnings: 'Approved with comments — human approval still required',
      changes_required: 'Changes requested',
      unable_to_complete: 'Review incomplete',
    },
    updateSuffix: (version) => `(update ${version})`,
    violates: 'violates',
    preExisting: 'Pre-existing, not introduced by this change.',
    reconsidered: 'Reconsidered since the previous review',
    scopeLine: (reviewed, changed, exclusions) =>
      `${reviewed} of ${changed} changed files` +
      (exclusions.length ? ` — ${exclusions.join('; ')}` : ''),
    resolvedNote: (ids) => `Resolved since the previous review: ${ids.join(', ')}.`,
    fullRerunNote: (reason) => `Reviewed the full PR rather than only the new commits: ${reason}`,
    disclaimer:
      'This review was generated by an AI assistant and should be validated by a human reviewer.',
  },
  th: {
    commentStatus: {
      pass: 'No blocking issues found — ยังต้องรอคนอนุมัติ',
      pass_with_warnings: 'Approved with comments — ยังต้องรอคนอนุมัติ',
      changes_required: 'Changes requested',
      unable_to_complete: 'Review incomplete',
    },
    updateSuffix: (version) => `(รอบที่ ${version})`,
    violates: 'ขัดกับ',
    preExisting: 'เป็นของเดิม ไม่ได้เกิดจากการแก้ครั้งนี้',
    reconsidered: 'เปลี่ยนข้อสรุปจากรีวิวรอบก่อน',
    scopeLine: (reviewed, changed, exclusions) =>
      `${reviewed} จาก ${changed} ไฟล์ที่เปลี่ยน` +
      (exclusions.length ? ` — ${exclusions.join('; ')}` : ''),
    resolvedNote: (ids) => `แก้แล้วตั้งแต่รีวิวรอบก่อน: ${ids.join(', ')}`,
    fullRerunNote: (reason) => `รีวิวเต็มทั้ง PR แทนที่จะรีวิวเฉพาะ commit ใหม่ เพราะ${reason}`,
    disclaimer: 'รีวิวนี้สร้างโดย AI และควรได้รับการตรวจสอบโดยผู้รีวิวที่เป็นคน',
  },
};

export function strings(lang) {
  const prose = PROSE[lang];
  if (!prose) throw new Error(`ไม่รองรับภาษา: ${lang}`);
  return { ...CHROME, ...prose };
}
